apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nbno
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-nbno@sha256:78ad38c68069359bca3c4d93f2d1167fdc7735a96fc92ee8cc90e6580e0ce8b0
        name: my-nodejs
        resources: {}
status: {}
